name: Auto Approve and Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    if: contains(fromJSON('["onatyy"]'), github.event.pull_request.user.login)
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.BOT_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
